/**
 * Profile prompts. The three core prompts are always shown in the edit form;
 * the pool feeds the "Suggest a prompt" button, which offers a random prompt
 * the attendee hasn't answered yet. Prompts are stored by their text, so
 * renaming one here leaves already-answered profiles unchanged.
 */

export const CORE_PROMPTS = ["Ask me about", "Looking for", "Offering"];

export const PROMPT_POOL: string[] = [
  "A hill I will die on",
  "A question I'm currently sitting with",
  "The rabbit hole I fell down recently",
  "Something I know way too much about",
  "Something I made recently",
  "I could talk for hours about",
  "My weirdest skill",
  "A book that rewired my brain",
  "I recently changed my mind about",
  "My favorite failure",
  "Teach me something about",
  "Currently obsessed with",
  "The best advice I ever ignored",
  "A problem I'd love help with",
  "What I'd do with a free year",
  "A place that shaped me",
  "Something I'm unlearning",
  "My current experiment",
  "A conversation I'm hoping to have here",
  "The last thing that genuinely amazed me",
  "I collect",
  "A tradition I invented",
  "An unusual habit that works for me",
  "The most useful thing I own",
  "A prediction I'm oddly confident about",
  "What I notice that most people miss",
  "If I had a second career, it would be",
  "A mystery I'd love to see solved",
  "The best thing I ever built with my hands",
  "A skill I'm building this year",
  "My comfort activity",
  "Something beautiful I saw recently",
  "A tiny thing that makes my day",
  "The strangest job I ever had",
  "A rule I always break",
  "What gets me out of bed in the morning",
  "My most controversial food opinion",
  "A historical figure I'd share a meal with",
  "The tool I can't live without",
  "Something I memorized and never regretted",
  "A sound I love",
  "My favorite question to ask strangers",
  "The subject I wish schools taught",
  "A small act of kindness I still remember",
  "What I'm deliberately bad at",
  "A belief I hold that few people share",
  "The most interesting mistake in my field",
  "Something I do differently since last year",
  "A game I'll always say yes to",
  "My relationship with deadlines",
  "A word or phrase from another language we should adopt",
  "The documentary I recommend to everyone",
  "Something I'm saving up courage for",
  "A pattern I keep seeing everywhere",
  "My favorite way to waste an afternoon",
  "The compliment I never forgot",
  "A niche internet community I love",
  "What my younger self would find surprising about me",
  "The thing I always overpack",
  "A ritual that keeps me sane",
];
